### ISSUE TITLE
Could this bundle work with the symfony 6 DATABASE_URL environment variable?

### ISSUE THREAD

**Issue by Andreas-Schoenefeldt** [Symandy/DatabaseBackupBundle#4]
Hello,

at the moment the bundle requires a explicit setup of dw user, password, name, etc - is there a chance, this could simply take the `DATABASE_URL` .env variable?

Thx a lot!
Andreas

**Comment by SVillette** [comment]
Thanks again for your feedback @Andreas-Schoenefeldt.
I guess it should simplify a lot the configuration of the bundle. I did not do it in the first place because I wanted users to be able to backup multiple databases with different configurations in only one file.

**Comment by Andreas-Schoenefeldt** [comment]
Maybe both can be supported? The standard usecase is probably to simply backup the configured database.

**Comment by SVillette** [comment]
Ofc it sounds logic, but it wasn't my use case when I created this bundle.
I will try to implement it soon.

**Comment by Andreas-Schoenefeldt** [comment]
Thx Mate!

**Comment by SVillette** [comment]
Sorry it took so long, I couldn't figure why the CI failed all the time
